"""恶意软件特征库扩充（大厂级覆盖：勒索/木马/RAT/间谍/僵尸/蠕虫/广告/黑客工具）。

本文件与 detector.py 的 MALWARE_PATTERNS 基础库合并，
覆盖常见恶意软件家族的真实可执行文件名/进程名关键字。
匹配逻辑：关键字小写，匹配"进程名+路径"组合。
"""
from ..schemas import RiskLevel

# 格式: (匹配关键字, 名称, 描述, 风险级别)
MALWARE_PATTERNS_EXT: list[tuple[str, str, str, RiskLevel]] = [
    # ═══ 勒索病毒家族（Ransomware）═══
    ("lockbit", "勒索病毒 LockBit", "全球最活跃的勒索软件家族之一，加密文件并勒索赎金", RiskLevel.CRITICAL),
    ("lockbit3", "勒索病毒 LockBit 3.0", "LockBit 第三代变种，双重勒索模式", RiskLevel.CRITICAL),
    ("conti", "勒索病毒 Conti", "大型勒索软件组织，针对企业内网传播", RiskLevel.CRITICAL),
    ("ryuk", "勒索病毒 Ryuk", "定向勒索攻击常用，加密整个网络", RiskLevel.CRITICAL),
    ("revil", "勒索病毒 REvil", "Sodinokibi 勒索家族，勒索金额巨大", RiskLevel.CRITICAL),
    ("sodinokibi", "勒索病毒 Sodinokibi", "REvil 勒索软件别名", RiskLevel.CRITICAL),
    ("blackcat", "勒索病毒 BlackCat", "ALPHV 勒索家族，Rust 编写", RiskLevel.CRITICAL),
    ("alphv", "勒索病毒 ALPHV", "BlackCat 勒索软件组织", RiskLevel.CRITICAL),
    ("wannacry", "勒索病毒 WannaCry", "利用永恒之蓝传播的全球性勒索病毒（2017）", RiskLevel.CRITICAL),
    ("wannacrypt", "勒索病毒 WannaCrypt", "WannaCry 勒索病毒内核", RiskLevel.CRITICAL),
    ("petya", "勒索病毒 Petya", "感染主引导记录的勒索软件", RiskLevel.CRITICAL),
    ("notpetya", "勒索病毒 NotPetya", "伪装勒索的破坏性蠕虫（2017）", RiskLevel.CRITICAL),
    ("badrabbit", "勒索病毒 Bad Rabbit", "通过伪装 Flash 安装包传播的勒索病毒", RiskLevel.CRITICAL),
    ("bad rabbit", "勒索病毒 Bad Rabbit", "Bad Rabbit 勒索病毒", RiskLevel.CRITICAL),
    ("cerber", "勒索病毒 Cerber", "勒索软件即服务（RaaS）先驱", RiskLevel.CRITICAL),
    ("gandcrab", "勒索病毒 GandCrab", "曾最活跃的勒索家族之一", RiskLevel.CRITICAL),
    ("grandcrab", "勒索病毒 GrandCrab", "GandCrab 勒索病毒", RiskLevel.CRITICAL),
    ("dharma", "勒索病毒 Dharma", "Crysis 勒索家族后代，RDP 爆破传播", RiskLevel.CRITICAL),
    ("crysis", "勒索病毒 Crysis", "勒索软件家族（2016）", RiskLevel.CRITICAL),
    ("phobos", "勒索病毒 Phobos", "Dharma 变种勒索家族", RiskLevel.CRITICAL),
    ("djvu", "勒索病毒 STOP/Djvu", "最流行的个人用户勒索病毒，.djvu 后缀", RiskLevel.CRITICAL),
    ("stop ransomware", "勒索病毒 STOP", "Djvu 勒索病毒家族", RiskLevel.CRITICAL),
    ("makop", "勒索病毒 Makop", "持续活跃的勒索家族", RiskLevel.CRITICAL),
    ("avaddon", "勒索病毒 Avaddon", "勒索软件即服务家族", RiskLevel.CRITICAL),
    ("clop", "勒索病毒 Clop", "针对企业的勒索组织", RiskLevel.CRITICAL),
    ("maze", "勒索病毒 Maze", "双重勒索模式开创者", RiskLevel.CRITICAL),
    ("egregor", "勒索病毒 Egregor", "Maze 后继勒索家族", RiskLevel.CRITICAL),
    ("netwalker", "勒索病毒 NetWalker", "Mailto 勒索家族，勒索金额高", RiskLevel.CRITICAL),
    ("mailto", "勒索病毒 Mailto", "NetWalker 勒索病毒别名", RiskLevel.CRITICAL),
    ("darkside", "勒索病毒 DarkSide", "针对管道等关键基础设施的勒索组织", RiskLevel.CRITICAL),
    ("dark side", "勒索病毒 DarkSide", "DarkSide 勒索软件", RiskLevel.CRITICAL),
    ("babuk", "勒索病毒 Babuk", "勒索软件家族，曾攻击体育组织", RiskLevel.CRITICAL),
    ("hive", "勒索病毒 Hive", "双重勒索组织，活跃 2021-2023", RiskLevel.CRITICAL),
    ("blackbasta", "勒索病毒 Black Basta", "2022 年起活跃的勒索组织", RiskLevel.CRITICAL),
    ("black basta", "勒索病毒 Black Basta", "Black Basta 勒索病毒", RiskLevel.CRITICAL),
    ("akira", "勒索病毒 Akira", "2023 活跃勒索家族，Linux/Windows 双平台", RiskLevel.CRITICAL),
    ("qilin", "勒索病毒 Qilin", "Agenda 勒索家族变种", RiskLevel.CRITICAL),
    ("cryptolocker", "勒索病毒 CryptoLocker", "经典勒索病毒（2013）", RiskLevel.CRITICAL),
    ("cryptowall", "勒索病毒 CryptoWall", "大规模传播的勒索家族", RiskLevel.CRITICAL),
    ("locky", "勒索病毒 Locky", "通过钓鱼邮件附件传播的勒索病毒", RiskLevel.CRITICAL),
    ("teslacrypt", "勒索病毒 TeslaCrypt", "针对游戏的勒索病毒", RiskLevel.CRITICAL),
    ("samsam", "勒索病毒 SamSam", "手工入侵服务器的勒索家族", RiskLevel.CRITICAL),
    ("globeimposter", "勒索病毒 GlobeImposter", "伪装 Globe 家族的勒索病毒", RiskLevel.CRITICAL),
    ("vxlocker", "勒索病毒 VxLocker", "加密后改名文件的勒索病毒", RiskLevel.CRITICAL),
    ("mole", "勒索病毒 Mole", "勒索病毒家族", RiskLevel.CRITICAL),
    ("magneto", "勒索病毒 Magneto", "Magniber 勒索变种家族", RiskLevel.CRITICAL),
    ("magniber", "勒索病毒 Magniber", "通过浏览器漏洞传播的勒索病毒", RiskLevel.CRITICAL),
    ("ransomware", "勒索病毒", "勒索软件通用特征", RiskLevel.CRITICAL),

    # ═══ 木马 / 远控 RAT ═══
    ("njrat", "远控木马 njRAT", "经典远控木马，常被用于窃取屏幕和文件", RiskLevel.CRITICAL),
    ("gh0st", "远控木马 Gh0st", "开源远控木马，中国黑客组织常用", RiskLevel.CRITICAL),
    ("ghost rat", "远控木马 Gh0st RAT", "Gh0st 远控木马", RiskLevel.CRITICAL),
    ("poisonivy", "远控木马 Poison Ivy", "经典远控木马（2005）", RiskLevel.CRITICAL),
    ("poison ivy", "远控木马 Poison Ivy", "Poison Ivy 远控木马", RiskLevel.CRITICAL),
    ("darkcomet", "远控木马 DarkComet", "知名远控木马", RiskLevel.CRITICAL),
    ("xrat", "远控木马 XRAT", "远程访问木马", RiskLevel.CRITICAL),
    ("imminent", "远控木马 Imminent Monitor", "商业远控被滥用为木马", RiskLevel.CRITICAL),
    ("nanorat", "远控木马 NanoCore RAT", "功能强大的远程访问木马", RiskLevel.CRITICAL),
    ("nanocore", "远控木马 NanoCore", "NanoCore RAT 家族", RiskLevel.CRITICAL),
    ("orcus", "远控木马 Orcus RAT", "C# 编写的远控木马", RiskLevel.CRITICAL),
    ("asyncrat", "远控木马 AsyncRAT", "开源远控木马，常捆绑钓鱼邮件传播", RiskLevel.CRITICAL),
    ("njw0rm", "远控木马 NJW0rm", "njRAT 变种", RiskLevel.CRITICAL),
    ("limes", "远控木马 Lime RAT", "跨平台远控木马", RiskLevel.CRITICAL),
    ("adwind", "跨平台木马 Adwind", "Java 跨平台远控木马（jRAT）", RiskLevel.CRITICAL),
    ("jrat", "远控木马 jRAT", "Java 远控木马", RiskLevel.CRITICAL),
    ("nastyr", "远控木马 Nasty Rat", "轻量级远控木马", RiskLevel.CRITICAL),
    ("quasar", "远控木马 Quasar RAT", "开源 C# 远控木马", RiskLevel.CRITICAL),
    ("cobian", "远控木马 Cobian RAT", "远控木马家族", RiskLevel.CRITICAL),
    ("fudrat", "远控木马 FUD RAT", "免杀远控木马", RiskLevel.CRITICAL),
    ("hacksaw", "远控木马 Hacksaw", "远控木马", RiskLevel.CRITICAL),
    ("remcos", "远控木马 Remcos", "商业远控被滥用于攻击", RiskLevel.CRITICAL),
    ("bifrost", "远控木马 Bifrost", "经典远控木马", RiskLevel.CRITICAL),
    ("netbus", "远控木马 NetBus", "经典远控木马（1998）", RiskLevel.CRITICAL),
    ("subseven", "远控木马 SubSeven", "经典远控木马", RiskLevel.CRITICAL),
    ("bo2k", "后门 Back Orifice 2000", "经典后门程序", RiskLevel.CRITICAL),
    ("radmin", "远控 Radmin", "被滥用的远程控制软件（非授权使用）", RiskLevel.HIGH),
    ("vncserver", "VNC 服务", "被滥用的远程桌面服务（非授权安装）", RiskLevel.HIGH),
    ("teamviewer", "远控 TeamViewer", "被滥用的远程控制软件（非授权使用）", RiskLevel.MEDIUM),

    # ═══ 信息窃取 / 键盘记录 ═══
    ("agenttesla", "窃密木马 Agent Tesla", "键盘记录+窃密木马，钓鱼邮件传播", RiskLevel.CRITICAL),
    ("agent tesla", "窃密木马 Agent Tesla", "Agent Tesla 窃密木马", RiskLevel.CRITICAL),
    ("azorult", "窃密木马 Azorult", "窃取凭据和加密货币的木马", RiskLevel.CRITICAL),
    ("redline", "窃密木马 RedLine Stealer", "窃取浏览器密码/钱包的窃密木马", RiskLevel.CRITICAL),
    ("redline stealer", "窃密木马 RedLine", "RedLine 窃密木马", RiskLevel.CRITICAL),
    ("racoon", "窃密木马 Raccoon Stealer", "窃取浏览器数据的窃密木马", RiskLevel.CRITICAL),
    ("raccoon stealer", "窃密木马 Raccoon", "Raccoon 窃密木马", RiskLevel.CRITICAL),
    ("vidar", "窃密木马 Vidar", "信息窃取木马", RiskLevel.CRITICAL),
    ("arkei", "窃密木马 Arkei", "信息窃取木马", RiskLevel.CRITICAL),
    ("predator", "窃密木马 Predator Stealer", "信息窃取木马", RiskLevel.CRITICAL),
    ("formbook", "窃密木马 FormBook", "键盘记录+表单窃取木马", RiskLevel.CRITICAL),
    ("lokibot", "窃密木马 LokiBot", "窃取浏览器凭据的银行木马", RiskLevel.CRITICAL),
    ("keylogger", "键盘记录器", "记录键盘输入，窃取密码", RiskLevel.CRITICAL),
    ("ardamax", "键盘记录器 Ardamax", "商业键盘记录器被滥用", RiskLevel.CRITICAL),
    ("spyrix", "间谍软件 Spyrix", "键盘记录+截屏间谍软件", RiskLevel.CRITICAL),
    ("stealer", "窃密木马", "信息窃取木马通用特征", RiskLevel.CRITICAL),
    ("hawkkey", "键盘记录器 HawkKey", "键盘记录器", RiskLevel.CRITICAL),
    ("screenshotter", "截屏间谍", "截屏窃密工具", RiskLevel.HIGH),

    # ═══ 僵尸网络 ═══
    ("emotet", "僵尸网络 Emotet", "全球最大僵尸网络之一，银行木马+垃圾邮件分发器", RiskLevel.CRITICAL),
    ("trickbot", "僵尸网络 TrickBot", "银行木马，常与勒索病毒配合", RiskLevel.CRITICAL),
    ("qakbot", "僵尸网络 QakBot", "银行木马，攻击链入口", RiskLevel.CRITICAL),
    ("qbot", "僵尸网络 QBot", "QakBot 僵尸网络", RiskLevel.CRITICAL),
    ("zeus", "僵尸网络 Zeus", "经典银行木马（Zbot）", RiskLevel.CRITICAL),
    ("zbot", "僵尸网络 Zbot", "Zeus 银行木马", RiskLevel.CRITICAL),
    ("citadel", "僵尸网络 Citadel", "Zeus 变种银行木马", RiskLevel.CRITICAL),
    ("spyeye", "僵尸网络 SpyEye", "银行木马（2010）", RiskLevel.CRITICAL),
    ("conficker", "蠕虫 Conficker", "大规模蠕虫（2008），自我繁殖", RiskLevel.CRITICAL),
    ("downadup", "蠕虫 Downadup", "Conficker 蠕虫别名", RiskLevel.CRITICAL),
    ("mirai", "僵尸网络 Mirai", "IoT 僵尸网络（2016），DDoS 攻击", RiskLevel.CRITICAL),
    ("bashlite", "僵尸网络 BashLite", "IoT 僵尸网络", RiskLevel.CRITICAL),
    ("gafgyt", "僵尸网络 Gafgyt", "IoT 僵尸网络", RiskLevel.CRITICAL),
    ("necurs", "僵尸网络 Necurs", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("andromeda", "僵尸网络 Andromeda", "下载器僵尸网络", RiskLevel.CRITICAL),
    ("gamaredon", "僵尸网络 Gamaredon", "间谍组织僵尸网络", RiskLevel.CRITICAL),

    # ═══ 蠕虫 ═══
    ("slammer", "蠕虫 SQL Slammer", "极速传播蠕虫（2003）", RiskLevel.CRITICAL),
    ("blaster", "蠕虫 Blaster", "MSBlaster 蠕虫（2003）", RiskLevel.CRITICAL),
    ("sasser", "蠕虫 Sasser", "系统漏洞蠕虫（2004）", RiskLevel.CRITICAL),
    ("mydoom", "蠕虫 MyDoom", "传播最快的邮件蠕虫（2004）", RiskLevel.CRITICAL),
    ("netsky", "蠕虫 NetSky", "邮件蠕虫（2004）", RiskLevel.CRITICAL),
    ("bagle", "蠕虫 Bagle", "邮件蠕虫（2004）", RiskLevel.CRITICAL),
    ("sobig", "蠕虫 Sobig", "邮件蠕虫（2003）", RiskLevel.CRITICAL),
    ("klez", "蠕虫 Klez", "邮件蠕虫（2001）", RiskLevel.CRITICAL),
    ("nimda", "蠕虫 Nimda", "混合型蠕虫（2001）", RiskLevel.CRITICAL),
    ("code red", "蠕虫 Code Red", "Web 服务器蠕虫（2001）", RiskLevel.CRITICAL),
    ("codered", "蠕虫 CodeRed", "Code Red 蠕虫", RiskLevel.CRITICAL),
    ("worm", "蠕虫", "蠕虫通用特征", RiskLevel.CRITICAL),

    # ═══ 广告 / 流氓软件 PUP ═══
    ("conduit", "流氓软件 Conduit", "浏览器劫持/广告插件", RiskLevel.MEDIUM),
    ("dealply", "流氓软件 DealPly", "广告插件", RiskLevel.MEDIUM),
    ("crossrider", "广告插件 Crossrider", "浏览器广告插件", RiskLevel.MEDIUM),
    ("oemji", "流氓软件 OEMJI", "广告插件", RiskLevel.MEDIUM),
    ("toolbar", "流氓工具栏", "浏览器工具栏捆绑软件", RiskLevel.MEDIUM),
    ("adware", "广告软件", "广告软件通用特征", RiskLevel.MEDIUM),
    ("pup", "流氓软件 PUP", "潜在不需要的程序", RiskLevel.MEDIUM),
    ("browserhelper", "浏览器劫持插件", "浏览器辅助劫持插件", RiskLevel.MEDIUM),
    ("searchprotect", "流氓软件 SearchProtect", "劫持搜索引擎的流氓软件", RiskLevel.MEDIUM),
    ("supdate", "流氓软件 Software Update", "伪装更新的流氓软件", RiskLevel.MEDIUM),

    # ═══ 挖矿补充 ═══
    ("minerd", "挖矿木马 MinerD", "CPU 挖矿木马", RiskLevel.CRITICAL),
    ("cryptojacker", "挖矿木马", "网页/进程挖矿木马", RiskLevel.CRITICAL),
    ("jsecoin", "挖矿木马 JSEcoin", "浏览器挖矿脚本", RiskLevel.HIGH),
    ("coinhive", "挖矿木马 CoinHive", "经典浏览器挖矿脚本", RiskLevel.HIGH),
    ("nicehash", "挖矿程序 NiceHash", "挖矿平台程序（非授权使用）", RiskLevel.HIGH),
    ("cgminer", "挖矿程序 CGMiner", "GPU/ASIC 挖矿程序", RiskLevel.HIGH),
    ("bfgminer", "挖矿程序 BFGMiner", "FPGA 挖矿程序", RiskLevel.HIGH),
    ("sgminer", "挖矿程序 SGMiner", "GPU 挖矿程序", RiskLevel.HIGH),
    ("xmr-stak", "挖矿程序 XMR-Stak", "门罗币 CPU/GPU 挖矿器", RiskLevel.CRITICAL),
    ("xmr-stak-cpu", "挖矿程序 XMR-Stak", "门罗币 CPU 挖矿器", RiskLevel.CRITICAL),
    ("xmrrig", "挖矿木马 XMRig", "门罗币挖矿木马变体", RiskLevel.CRITICAL),
    ("kryptex", "挖矿程序 Kryptex", "挖矿平台程序", RiskLevel.MEDIUM),

    # ═══ 黑客工具 / 后渗透 ═══
    ("mimikatz", "黑客工具 Mimikatz", "窃取 Windows 凭据的著名黑客工具", RiskLevel.CRITICAL),
    ("responder", "黑客工具 Responder", "LLMNR/NBT-NS 投毒工具", RiskLevel.CRITICAL),
    ("psexec", "黑客工具 PsExec", "被滥用的远程执行工具", RiskLevel.HIGH),
    ("metasploit", "渗透框架 Metasploit", "渗透测试框架（被滥用时危险）", RiskLevel.CRITICAL),
    ("meterpreter", "渗透载荷 Meterpreter", "Metasploit 攻击载荷", RiskLevel.CRITICAL),
    ("cobaltstrike", "攻击框架 Cobalt Strike", "红队攻击框架（被滥用时危险）", RiskLevel.CRITICAL),
    ("cobalt strike", "攻击框架 Cobalt Strike", "Cobalt Strike 攻击框架", RiskLevel.CRITICAL),
    ("beacon", "攻击载荷 Beacon", "Cobalt Strike 木马载荷", RiskLevel.CRITICAL),
    ("empire", "攻击框架 Empire", "PowerShell 攻击框架", RiskLevel.CRITICAL),
    ("sliver", "攻击框架 Sliver", "开源 C2 攻击框架", RiskLevel.CRITICAL),
    ("havoc", "攻击框架 Havoc", "开源 C2 攻击框架", RiskLevel.CRITICAL),
    ("brute ratel", "攻击框架 Brute Ratel", "商业攻击框架被滥用", RiskLevel.CRITICAL),
    ("koadic", "攻击框架 Koadic", "Windows 后渗透工具", RiskLevel.CRITICAL),
    ("nishang", "攻击框架 Nishang", "PowerShell 攻击脚本库", RiskLevel.CRITICAL),
    ("powersploit", "攻击框架 PowerSploit", "PowerShell 后渗透框架", RiskLevel.CRITICAL),
    ("pwncat", "后门 PwnCat", "反弹 shell 后门工具", RiskLevel.CRITICAL),
    ("chisel", "隧道工具 Chisel", "被滥用的内网隧道工具", RiskLevel.CRITICAL),
    ("frpc", "隧道工具 Frp", "被滥用的内网穿透客户端", RiskLevel.HIGH),
    ("frps", "隧道工具 Frp 服务端", "被滥用的内网穿透服务端", RiskLevel.HIGH),
    ("nps", "隧道工具 NPS", "被滥用的内网穿透工具", RiskLevel.HIGH),
    ("ngrok", "隧道工具 Ngrok", "被滥用的内网穿透工具", RiskLevel.MEDIUM),
    ("socat", "隧道工具 Socat", "被滥用的网络隧道工具", RiskLevel.HIGH),
    ("plink", "隧道工具 Plink", "被滥用的 SSH 隧道工具", RiskLevel.MEDIUM),
    ("reGeorg", "代理工具 reGeorg", "WebShell 代理工具", RiskLevel.CRITICAL),
    ("sqlmap", "注入工具 SQLMap", "SQL 注入自动化工具（被滥用时危险）", RiskLevel.HIGH),
    ("nuclei", "扫描工具 Nuclei", "漏洞扫描工具（被滥用时危险）", RiskLevel.HIGH),
    ("hydra", "爆破工具 Hydra", "口令爆破工具", RiskLevel.CRITICAL),
    ("john", "爆破工具 John the Ripper", "密码破解工具", RiskLevel.HIGH),
    ("hashcat", "爆破工具 Hashcat", "GPU 密码破解工具", RiskLevel.HIGH),
    ("medusa", "爆破工具 Medusa", "口令爆破工具", RiskLevel.CRITICAL),
    ("crackmapexec", "攻击工具 CrackMapExec", "内网横向移动工具", RiskLevel.CRITICAL),
    ("nmap", "扫描工具 Nmap", "网络扫描工具（被滥用时危险）", RiskLevel.MEDIUM),
    ("masscan", "扫描工具 Masscan", "高速端口扫描工具", RiskLevel.MEDIUM),
    ("zmap", "扫描工具 Zmap", "全网扫描工具", RiskLevel.MEDIUM),
    ("burpsuite", "测试工具 Burp Suite", "Web 安全测试工具（被滥用时危险）", RiskLevel.MEDIUM),
    ("beef", "攻击框架 BeEF", "浏览器攻击框架", RiskLevel.HIGH),
    ("webshell", "WebShell", "网站后门脚本", RiskLevel.CRITICAL),
    ("shell.php", "WebShell", "PHP WebShell 后门", RiskLevel.CRITICAL),
    ("cmd.php", "WebShell", "命令执行 WebShell", RiskLevel.CRITICAL),

    # ═══ 其他恶意/高危 ═══
    ("keygen", "盗版破解工具 Keygen", "常捆绑恶意软件的破解工具", RiskLevel.HIGH),
    ("crack", "破解工具", "常捆绑恶意软件的破解工具", RiskLevel.HIGH),
    ("loader", "木马加载器 Loader", "恶意软件加载器", RiskLevel.HIGH),
    ("dropper", "木马投放器 Dropper", "恶意软件投放器", RiskLevel.CRITICAL),
    ("download", "下载器木马", "恶意软件下载器", RiskLevel.HIGH),
    ("banker", "银行木马", "窃取网银凭据的木马", RiskLevel.CRITICAL),
    ("spyware", "间谍软件", "间谍软件通用特征", RiskLevel.CRITICAL),
    ("backdoor", "后门程序", "后门通用特征", RiskLevel.CRITICAL),
    ("rootkit", "Rootkit", "隐藏自身的高级恶意程序", RiskLevel.CRITICAL),
    ("bootkit", "Bootkit", "感染引导区的恶意程序", RiskLevel.CRITICAL),
    ("trickster", "木马 Trickster", "恶意软件家族", RiskLevel.CRITICAL),
    ("snake keylogger", "键盘记录器 Snake", "键盘记录木马", RiskLevel.CRITICAL),
    ("hawkeye", "键盘记录器 HawkEye", "键盘记录+窃密木马", RiskLevel.CRITICAL),
    ("icedid", "木马 IcedID", "银行木马，勒索攻击入口", RiskLevel.CRITICAL),
    ("bokbot", "木马 BokBot", "银行木马", RiskLevel.CRITICAL),
    ("dridex", "银行木马 Dridex", "银行木马（2014）", RiskLevel.CRITICAL),
    ("urlzone", "银行木马 URLZone", "银行木马", RiskLevel.CRITICAL),
    ("cridex", "银行木马 Cridex", "银行木马", RiskLevel.CRITICAL),
    ("shylock", "银行木马 Shylock", "银行木马", RiskLevel.CRITICAL),
    ("neverquest", "银行木马 NeverQuest", "银行木马", RiskLevel.CRITICAL),
    ("vawtrak", "银行木马 Vawtrak", "银行木马", RiskLevel.CRITICAL),
    ("dana bot", "银行木马 DanaBot", "银行木马", RiskLevel.CRITICAL),
    ("zinjai", "银行木马 ZinjaI", "银行木马", RiskLevel.CRITICAL),
    ("gozi", "银行木马 Gozi", "银行木马（2007）", RiskLevel.CRITICAL),
    ("snifula", "银行木马 Snifula", "银行木马", RiskLevel.CRITICAL),
    ("ramnit", "银行木马 Ramnit", "银行木马+蠕虫", RiskLevel.CRITICAL),
    ("ursnif", "银行木马 Ursnif", "银行木马（Dreambot）", RiskLevel.CRITICAL),
    ("dreambot", "银行木马 Dreambot", "Ursnif 银行木马变种", RiskLevel.CRITICAL),
    ("isoknife", "银行木马 Isoknife", "银行木马", RiskLevel.CRITICAL),
    ("kjw0rm", "蠕虫 KjW0rm", "远控蠕虫", RiskLevel.CRITICAL),
    ("gamarue", "木马 Gamarue", "下载器木马", RiskLevel.CRITICAL),
    ("winwebsec", "流氓软件 WinWebSec", "恐吓型流氓杀毒", RiskLevel.HIGH),
    ("fakerean", "流氓软件 FakeRean", "恐吓型流氓杀毒", RiskLevel.HIGH),
    ("ranscam", "流氓软件 Ranscam", "恐吓型流氓软件", RiskLevel.HIGH),

    # ═══ 扩充二：游戏盗号 / 外挂捆绑 ═══
    ("steam stealer", "Steam 盗号木马", "窃取 Steam 账号的木马", RiskLevel.CRITICAL),
    ("gamehack", "游戏外挂", "游戏外挂，常捆绑木马", RiskLevel.HIGH),
    ("game hack", "游戏外挂", "游戏外挂捆绑木马", RiskLevel.HIGH),
    ("hacktool", "游戏外挂", "游戏外挂工具", RiskLevel.HIGH),
    ("cheat engine", "游戏修改器 Cheat Engine", "游戏修改器（被恶意捆绑时危险）", RiskLevel.MEDIUM),
    ("xigncode", "反作弊注入", "被滥用的反作弊程序", RiskLevel.MEDIUM),
    ("wpe", "抓包工具 WPE", "游戏抓包工具（被滥用时危险）", RiskLevel.MEDIUM),
    ("盗号", "盗号木马", "账号窃取木马", RiskLevel.CRITICAL),
    ("qq木马", "QQ 盗号木马", "窃取 QQ 账号的木马", RiskLevel.CRITICAL),
    ("游戏木马", "游戏盗号木马", "窃取游戏账号的木马", RiskLevel.CRITICAL),

    # ═══ 扩充三：下载器 / 捆绑器 ═══
    ("softpulse", "捆绑器 SoftPulse", "软件捆绑安装器", RiskLevel.MEDIUM),
    ("installcore", "捆绑器 InstallCore", "恶意软件捆绑安装器", RiskLevel.MEDIUM),
    ("opencandy", "捆绑器 OpenCandy", "广告捆绑安装器", RiskLevel.MEDIUM),
    ("bundle", "捆绑器", "恶意软件捆绑安装器", RiskLevel.MEDIUM),
    ("setup_", "可疑安装器", "可疑安装程序", RiskLevel.LOW),
    ("updater.exe", "可疑更新器", "伪装系统更新的程序", RiskLevel.HIGH),
    ("winupdate", "伪装更新器", "伪装 Windows 更新的恶意程序", RiskLevel.CRITICAL),
    ("windowsupdate.exe", "伪装更新器", "伪装 Windows 更新的恶意程序", RiskLevel.CRITICAL),
    ("svch0st", "伪装进程", "伪装系统进程的恶意程序", RiskLevel.CRITICAL),
    ("svchosts", "伪装进程", "伪装 svchost 的恶意程序", RiskLevel.CRITICAL),
    ("csrss_.exe", "伪装进程", "伪装 csrss 的恶意程序", RiskLevel.CRITICAL),
    ("expl0rer", "伪装进程", "伪装 explorer 的恶意程序", RiskLevel.CRITICAL),
    ("winlog0n", "伪装进程", "伪装 winlogon 的恶意程序", RiskLevel.CRITICAL),
    ("lsass_.exe", "伪装进程", "伪装 lsass 的恶意程序", RiskLevel.CRITICAL),
    ("services_.exe", "伪装进程", "伪装 services 的恶意程序", RiskLevel.CRITICAL),
    ("system32.exe", "伪装进程", "伪装系统目录的恶意程序", RiskLevel.CRITICAL),

    # ═══ 扩充四：APT / 国家背景工具 ═══
    ("kimsuky", "APT 组织工具 Kimsuky", "朝鲜背景 APT 组织工具", RiskLevel.CRITICAL),
    ("lazarus", "APT 组织工具 Lazarus", "朝鲜背景 APT 组织（2014 索尼攻击）", RiskLevel.CRITICAL),
    ("apt29", "APT29 工具", "俄罗斯背景 APT 组织（Cozy Bear）", RiskLevel.CRITICAL),
    ("apt28", "APT28 工具", "俄罗斯背景 APT 组织（Fancy Bear）", RiskLevel.CRITICAL),
    ("turla", "APT 组织工具 Turla", "俄罗斯背景 APT 组织", RiskLevel.CRITICAL),
    ("fancybear", "APT28 Fancy Bear", "APT28 组织工具", RiskLevel.CRITICAL),
    ("cozybear", "APT29 Cozy Bear", "APT29 组织工具", RiskLevel.CRITICAL),
    ("oceanlotus", "APT 组织 OceanLotus", "越南背景 APT 组织", RiskLevel.CRITICAL),
    ("apt10", "APT10 工具", "云衍生组织工具", RiskLevel.CRITICAL),
    ("apt41", "APT41 工具", "双重心 APT 组织", RiskLevel.CRITICAL),
    ("winnti", "APT 组织 Winnti", "Winnti 组织后门", RiskLevel.CRITICAL),
    ("wmi backdoor", "WMI 后门", "利用 WMI 的持久化后门", RiskLevel.CRITICAL),
    ("dnscat", "DNS 隧道工具 dnscat2", "DNS 隧道通信工具", RiskLevel.CRITICAL),
    ("squirtle", "DNS 隧道工具", "DNS 隧道工具", RiskLevel.HIGH),
    ("iodine", "DNS 隧道工具 Iodine", "DNS 隧道工具", RiskLevel.HIGH),

    # ═══ 扩充五：勒索变种补充 ═══
    ("tellYouThePass", "勒索病毒 TellYouThePass", "2023 活跃勒索家族", RiskLevel.CRITICAL),
    ("wallet", "勒索病毒 Wallet", "勒索病毒家族", RiskLevel.CRITICAL),
    ("xdata", "勒索病毒 XData", "勒索病毒家族", RiskLevel.CRITICAL),
    ("crypt0l0cker", "勒索病毒 CryptoLocker", "CryptoLocker 变种", RiskLevel.CRITICAL),
    ("purge", "勒索病毒 Purge", "勒索病毒家族", RiskLevel.CRITICAL),
    ("hakbit", "勒索病毒 Hakbit", "勒索病毒家族", RiskLevel.CRITICAL),
    ("xorist", "勒索病毒 Xorist", "勒索病毒家族", RiskLevel.CRITICAL),
    ("scarlet", "勒索病毒 Scarlet", "勒索病毒家族", RiskLevel.CRITICAL),
    ("jigsaw", "勒索病毒 Jigsaw", "倒计时删除文件的勒索病毒", RiskLevel.CRITICAL),
    ("hidden tear", "勒索病毒 Hidden Tear", "开源勒索病毒", RiskLevel.CRITICAL),
    ("hiddentear", "勒索病毒 HiddenTear", "Hidden Tear 勒索病毒", RiskLevel.CRITICAL),
    ("satana", "勒索病毒 Satana", "MBR 勒索病毒", RiskLevel.CRITICAL),
    ("dma locker", "勒索病毒 DMA Locker", "勒索病毒家族", RiskLevel.CRITICAL),
    ("chimera", "勒索病毒 Chimera", "勒索病毒家族", RiskLevel.CRITICAL),
    ("maktub", "勒索病毒 Maktub", "勒索病毒家族", RiskLevel.CRITICAL),
    ("cryptxxx", "勒索病毒 CryptXXX", "勒索病毒家族", RiskLevel.CRITICAL),
    ("cryptowall", "勒索病毒 CryptoWall", "勒索病毒家族", RiskLevel.CRITICAL),
    ("padcrypt", "勒索病毒 PadCrypt", "勒索病毒家族", RiskLevel.CRITICAL),
    ("nemucod", "勒索下载器 Nemucod", "勒索病毒下载器", RiskLevel.CRITICAL),
    ("wadhrama", "勒索病毒 Wadhrama", "Dharma 变种", RiskLevel.CRITICAL),
    ("venus locker", "勒索病毒 Venus Locker", "勒索病毒家族", RiskLevel.CRITICAL),
    ("hades", "勒索病毒 Hades", "勒索病毒家族", RiskLevel.CRITICAL),
    ("karma", "勒索病毒 Karma", "勒索病毒家族", RiskLevel.CRITICAL),
    ("yanluowang", "勒索病毒 Yanluowang", "勒索病毒家族", RiskLevel.CRITICAL),
    ("monti", "勒索病毒 Monti", "Linux 勒索病毒", RiskLevel.CRITICAL),
    ("pandora", "勒索病毒 Pandora", "勒索病毒家族", RiskLevel.CRITICAL),
    ("cryptonite", "勒索病毒 Cryptonite", "勒索病毒家族", RiskLevel.CRITICAL),
    ("leaker locker", "勒索病毒 LeakerLocker", "勒索病毒家族", RiskLevel.CRITICAL),
    ("fixtool", "勒索病毒 FixTool", "勒索病毒家族", RiskLevel.CRITICAL),

    # ═══ 扩充六：木马变种补充 ═══
    ("darktrack", "木马 DarkTrack", "远控木马", RiskLevel.CRITICAL),
    ("bluenoroff", "木马 BlueNoroff", "金融攻击木马", RiskLevel.CRITICAL),
    ("magicrAT", "木马 MagicRAT", "远控木马", RiskLevel.CRITICAL),
    ("crimson", "木马 Crimson RAT", "远控木马", RiskLevel.CRITICAL),
    ("thedude", "木马 TheDude", "远控木马", RiskLevel.CRITICAL),
    ("muddywater", "木马 MuddyWater", "APT 木马", RiskLevel.CRITICAL),
    ("kdcspy", "木马 KDSPy", "APT 木马", RiskLevel.CRITICAL),
    ("poulight", "木马 Poulight", "APT 木马", RiskLevel.CRITICAL),
    ("xagent", "木马 XAgent", "间谍木马", RiskLevel.CRITICAL),
    ("newt", "木马 Newt", "远控木马", RiskLevel.CRITICAL),
    ("httprat", "木马 HTTP RAT", "HTTP 远控木马", RiskLevel.CRITICAL),
    ("downloader", "下载器木马", "恶意软件下载器", RiskLevel.HIGH),
    ("wicked", "木马 Wicked", "远控木马", RiskLevel.CRITICAL),
    ("storm", "木马 Storm", "木马家族", RiskLevel.CRITICAL),
    ("necro", "木马 Necro", "木马家族", RiskLevel.CRITICAL),
    ("skygofree", "木马 Skygofree", "间谍木马", RiskLevel.CRITICAL),
    ("mosquito", "木马 Mosquito", "间谍木马", RiskLevel.CRITICAL),
    ("chrysaor", "木马 Chrysaor", "间谍木马", RiskLevel.CRITICAL),
    ("pcrat", "木马 PCRAT", "远控木马", RiskLevel.CRITICAL),
    ("ratty", "木马 Ratty", "远控木马", RiskLevel.CRITICAL),
    ("charcoal", "木马 Charcoal Stork", "远控木马", RiskLevel.CRITICAL),
    ("stork", "木马 Stork", "远控木马", RiskLevel.CRITICAL),
    ("redlurk", "木马 RedLurk", "远控木马", RiskLevel.CRITICAL),
    ("hworm", "木马 HWorm", "远控木马", RiskLevel.CRITICAL),
    ("xworm", "木马 XWorm", "远控木马", RiskLevel.CRITICAL),
    ("phoenix", "木马 Phoenix", "远控木马", RiskLevel.CRITICAL),
    ("fallen angel", "木马 Fallen Angel", "远控木马", RiskLevel.CRITICAL),
    ("fatalrat", "木马 FatalRAT", "远控木马", RiskLevel.CRITICAL),
    ("mwrat", "木马 MWRAT", "远控木马", RiskLevel.CRITICAL),
    ("vcrypt", "木马 VCrypt", "远控木马", RiskLevel.CRITICAL),

    # ═══ 扩充七：间谍/窃密补充 ═══
    ("stealc", "窃密木马 StealC", "信息窃取木马", RiskLevel.CRITICAL),
    ("lumma", "窃密木马 Lumma Stealer", "浏览器窃密木马", RiskLevel.CRITICAL),
    ("rhadamanthys", "窃密木马 Rhadamanthys", "信息窃取木马", RiskLevel.CRITICAL),
    ("risepro", "窃密木马 RisePro", "信息窃取木马", RiskLevel.CRITICAL),
    ("meduza", "窃密木马 Meduza Stealer", "信息窃取木马", RiskLevel.CRITICAL),
    ("white snake", "窃密木马 WhiteSnake", "信息窃取木马", RiskLevel.CRITICAL),
    ("whitesnake", "窃密木马 WhiteSnake", "信息窃取木马", RiskLevel.CRITICAL),
    ("amadey", "窃密木马 Amadey", "信息窃取木马", RiskLevel.CRITICAL),
    ("darkgate", "木马 DarkGate", "恶意软件加载器+窃密", RiskLevel.CRITICAL),
    ("matanbuchus", "木马 Matanbuchus", "恶意软件加载器", RiskLevel.CRITICAL),
    ("socgholish", "木马 SocGholish", "网站注入木马", RiskLevel.CRITICAL),
    ("guLoader", "木马 GuLoader", "恶意软件加载器", RiskLevel.CRITICAL),
    ("guloader", "木马 GuLoader", "恶意软件加载器", RiskLevel.CRITICAL),
    ("private loader", "木马 PrivateLoader", "恶意软件加载器", RiskLevel.CRITICAL),
    ("privateloader", "木马 PrivateLoader", "恶意软件加载器", RiskLevel.CRITICAL),
    ("prometei", "挖矿蠕虫 Prometei", "挖矿+蠕虫混合", RiskLevel.CRITICAL),
    ("cryptbot", "窃密木马 CryptBot", "浏览器窃密木马", RiskLevel.CRITICAL),
    ("ficker", "窃密木马 Ficker Stealer", "信息窃取木马", RiskLevel.CRITICAL),
    ("typo steal", "窃密木马 TypoStealer", "信息窃取木马", RiskLevel.CRITICAL),
    ("anonymous", "窃密木马 Anonymous Stealer", "信息窃取木马", RiskLevel.CRITICAL),
    ("scareware", "恐吓软件", "恐吓型软件", RiskLevel.HIGH),
    ("clipboard hijack", "剪贴板劫持", "劫持剪贴板窃取加密货币地址", RiskLevel.HIGH),
    ("clipboardhijack", "剪贴板劫持", "剪贴板劫持木马", RiskLevel.HIGH),
    ("cryptoclipper", "剪贴板劫持 CryptoClipper", "劫持加密货币地址的木马", RiskLevel.CRITICAL),
    ("wallet.dat", "钱包窃取", "窃取加密货币钱包文件的恶意程序", RiskLevel.CRITICAL),
    ("metamask stealer", "钱包窃取", "窃取浏览器钱包的木马", RiskLevel.CRITICAL),

    # ═══ 扩充八：挖矿补充 ═══
    ("pool.miner", "挖矿木马", "连接矿池的挖矿程序", RiskLevel.CRITICAL),
    ("minerstat", "挖矿程序 MinerStat", "挖矿管理程序", RiskLevel.HIGH),
    ("honeyminer", "挖矿程序 HoneyMiner", "挖矿程序", RiskLevel.HIGH),
    ("salad", "挖矿程序 Salad", "共享算力挖矿程序（非授权使用）", RiskLevel.HIGH),
    ("gpu miner", "挖矿程序", "GPU 挖矿程序", RiskLevel.HIGH),
    ("cpu miner", "挖矿程序", "CPU 挖矿程序", RiskLevel.CRITICAL),
    ("minergatecli", "挖矿程序 MinerGate", "MinerGate 挖矿客户端", RiskLevel.HIGH),
    ("ethminer64", "挖矿程序", "以太坊挖矿器 64 位", RiskLevel.HIGH),
    ("monero", "挖矿程序 Monero 矿工", "门罗币挖矿程序", RiskLevel.CRITICAL),
    ("kryptonian", "挖矿程序 Kryptonian", "挖矿程序", RiskLevel.HIGH),

    # ═══ 扩充九：僵尸/蠕虫补充 ═══
    ("sality", "病毒 Sality", "多态文件病毒+僵尸网络", RiskLevel.CRITICAL),
    ("virut", "病毒 Virut", "文件感染型病毒", RiskLevel.CRITICAL),
    ("ramdo", "病毒 Ramdo", "文件感染型病毒", RiskLevel.CRITICAL),
    ("waledac", "僵尸网络 Waledac", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("rustock", "僵尸网络 Rustock", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("cutwail", "僵尸网络 Cutwail", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("pusu", "僵尸网络 Pusu", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("srizbi", "僵尸网络 Srizbi", "垃圾邮件僵尸网络", RiskLevel.CRITICAL),
    ("mebroot", "Bootkit Mebroot", "MBR 感染型 Bootkit", RiskLevel.CRITICAL),
    ("tidserv", "Bootkit TDL4", "TDL4 Bootkit 家族", RiskLevel.CRITICAL),
    ("tdl4", "Bootkit TDL4", "高级 Bootkit 木马", RiskLevel.CRITICAL),
    ("sinowal", "Bootkit Sinowal", "MBR Bootkit", RiskLevel.CRITICAL),
    ("olmasco", "Bootkit Olmasco", "Bootkit 家族", RiskLevel.CRITICAL),
    ("gapz", "Bootkit Gapz", "Bootkit 家族", RiskLevel.CRITICAL),

    # ═══ 扩充十：其他 ═══
    ("keygen.exe", "破解工具", "常捆绑木马的破解器", RiskLevel.HIGH),
    ("patch.exe", "破解补丁", "常捆绑木马的破解补丁", RiskLevel.HIGH),
    ("activator", "激活工具", "常捆绑木马的激活工具", RiskLevel.HIGH),
    ("kms", "KMS 激活工具", "Windows/Office 激活工具（常捆绑恶意软件）", RiskLevel.MEDIUM),
    ("注册机", "注册机", "常捆绑木马的注册机", RiskLevel.HIGH),
    ("去广告", "去广告工具", "常捆绑流氓软件的清理工具", RiskLevel.MEDIUM),
    ("加速器", "游戏加速器", "常捆绑流氓软件的加速器", RiskLevel.MEDIUM),
    ("浏览器首页劫持", "浏览器劫持", "劫持浏览器首页的程序", RiskLevel.MEDIUM),
    ("dns劫持", "DNS 劫持", "篡改 DNS 设置的恶意程序", RiskLevel.CRITICAL),
    ("hosts劫持", "HOSTS 劫持", "篡改 hosts 文件的恶意程序", RiskLevel.CRITICAL),
    ("uac绕过", "UAC 绕过工具", "绕过 UAC 的工具", RiskLevel.HIGH),
    ("提权", "提权工具", "权限提升工具", RiskLevel.HIGH),
    ("屏幕录像", "屏幕录像间谍", "秘密屏幕录像工具", RiskLevel.HIGH),
    ("录音间谍", "录音间谍", "秘密录音工具", RiskLevel.HIGH),
    ("摄像头间谍", "摄像头间谍", "秘密开启摄像头的工具", RiskLevel.HIGH),
    ("webcam spy", "摄像头间谍", "秘密摄像头访问工具", RiskLevel.HIGH),
    ("spy cam", "摄像头间谍", "秘密摄像头工具", RiskLevel.HIGH),
    ("rat.exe", "远控木马", "远控木马可执行文件", RiskLevel.CRITICAL),
    ("server.exe", "远控服务端", "远控木马服务端", RiskLevel.CRITICAL),
    ("client.exe", "远控客户端", "远控木马客户端", RiskLevel.CRITICAL),
    ("\\shell.exe", "反弹 Shell", "独立的 shell.exe 可执行文件（非 powershell）", RiskLevel.CRITICAL),
    ("reverse shell", "反弹 Shell", "反弹 shell 工具", RiskLevel.CRITICAL),
    ("bind shell", "绑定 Shell", "绑定 shell 工具", RiskLevel.CRITICAL),
    ("payload", "攻击载荷", "攻击载荷通用特征", RiskLevel.HIGH),
    ("exploit", "漏洞利用", "漏洞利用程序", RiskLevel.HIGH),
]
