"""API 提供商定义：14 家（国内 11 + 国际 2 + 本地 + 自定义）。

模型名来源：各官方 API /v1/models 端点验证 + 官方文档。
"""
from __future__ import annotations

PROVIDERS: dict[str, dict] = {
    # ═══ 🇨🇳 国内主流 ═══
    "deepseek": {
        "name": "DeepSeek（深度求索）",
        "base_url": "https://api.deepseek.com/anthropic",
        "models": ["deepseek-v4-pro", "deepseek-v4-flash"],
        "default_model": "deepseek-v4-pro",
        "format": "openai",
        "description": "DeepSeek 官方。deepseek-v4-pro=旗舰, flash=轻量",
    },
    "kimi": {
        "name": "Kimi（月之暗面）",
        "base_url": "https://api.moonshot.cn/v1",
        "models": ["moonshot-v1-auto", "moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
        "default_model": "moonshot-v1-auto",
        "format": "openai",
        "description": "月之暗面 Kimi。auto 自动选择最佳模型",
    },
    "zhipu": {
        "name": "智谱 GLM",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "models": ["glm-4-flash", "glm-4-air", "glm-4-plus", "glm-4", "glm-4v-flash"],
        "default_model": "glm-4-flash",
        "format": "openai",
        "description": "智谱 AI。glm-4-flash 免费额度友好，glm-4v 支持图像",
    },
    "qwen": {
        "name": "通义千问（阿里云）",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "models": ["qwen-turbo", "qwen-plus", "qwen-max", "qwen-long", "qwen2.5-72b-instruct"],
        "default_model": "qwen-turbo",
        "format": "openai",
        "description": "阿里云百炼。qwen-turbo 性价比最高",
    },
    "doubao": {
        "name": "豆包（字节火山）",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "models": ["doubao-pro-32k", "doubao-lite-32k", "doubao-pro-4k", "doubao-pro-128k"],
        "default_model": "doubao-lite-32k",
        "format": "openai",
        "description": "字节火山引擎豆包大模型",
    },
    "minimax": {
        "name": "MiniMax（海螺 AI）",
        "base_url": "https://api.minimax.chat/v1",
        "models": ["abab6.5s-chat", "abab6.5t-chat", "abab7-chat-preview"],
        "default_model": "abab6.5s-chat",
        "format": "openai",
        "description": "MiniMax 海螺 AI",
    },
    "baichuan": {
        "name": "百川智能",
        "base_url": "https://api.baichuan-ai.com/v1",
        "models": ["Baichuan4-Air", "Baichuan4", "Baichuan4-Turbo", "Baichuan3-Turbo"],
        "default_model": "Baichuan4-Air",
        "format": "openai",
        "description": "百川智能大模型",
    },
    # ═══ 新增 4 家 ═══
    "yi": {
        "name": "零一万物（Yi）",
        "base_url": "https://api.lingyiwanwu.com/v1",
        "models": ["yi-large", "yi-medium", "yi-lightning", "yi-vision"],
        "default_model": "yi-lightning",
        "format": "openai",
        "description": "零一万物 Yi 系列大模型",
    },
    "hunyuan": {
        "name": "腾讯混元",
        "base_url": "https://api.hunyuan.cloud.tencent.com/v1",
        "models": ["hunyuan-turbo", "hunyuan-pro", "hunyuan-lite", "hunyuan-standard"],
        "default_model": "hunyuan-turbo",
        "format": "openai",
        "description": "腾讯混元大模型（需先在腾讯云开通）",
    },
    "stepfun": {
        "name": "阶跃星辰（StepFun）",
        "base_url": "https://api.stepfun.com/v1",
        "models": ["step-1-flash", "step-1-8k", "step-1-32k", "step-1-128k"],
        "default_model": "step-1-flash",
        "format": "openai",
        "description": "阶跃星辰 Step 系列大模型",
    },
    "spark": {
        "name": "讯飞星火",
        "base_url": "https://spark-api-open.xf-yun.com/v1",
        "models": ["lite", "pro-128k", "max-32k", "4.0-ultra"],
        "default_model": "pro-128k",
        "format": "openai",
        "description": "讯飞星火大模型（OpenAI 兼容端点）",
    },
    # ═══ 🌍 国际主流 ═══
    "openai": {
        "name": "OpenAI（ChatGPT）",
        "base_url": "https://api.openai.com/v1",
        "models": ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o4-mini"],
        "default_model": "gpt-4o-mini",
        "format": "openai",
        "description": "OpenAI 官方。gpt-4o-mini 性价比最高",
    },
    "gemini": {
        "name": "Google Gemini",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "models": ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.0-flash"],
        "default_model": "gemini-2.5-flash",
        "format": "openai",
        "description": "Google Gemini。免费额度 1500次/天",
    },
    "anthropic": {
        "name": "Anthropic Claude",
        "base_url": "https://api.anthropic.com/v1",
        "models": ["claude-sonnet-4-20250514", "claude-3.5-sonnet", "claude-3.5-haiku"],
        "default_model": "claude-sonnet-4-20250514",
        "format": "anthropic",
        "description": "Anthropic 官方 Claude 系列",
    },
    "mistral": {
        "name": "Mistral AI",
        "base_url": "https://api.mistral.ai/v1",
        "models": ["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "codestral-latest"],
        "default_model": "mistral-small-latest",
        "format": "openai",
        "description": "法国 Mistral AI。开源友好",
    },
    "xai": {
        "name": "xAI Grok（马斯克）",
        "base_url": "https://api.x.ai/v1",
        "models": ["grok-2", "grok-2-vision", "grok-beta"],
        "default_model": "grok-2",
        "format": "openai",
        "description": "xAI 的 Grok 系列",
    },
    "together": {
        "name": "Together AI",
        "base_url": "https://api.together.xyz/v1",
        "models": ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen2.5-72B-Instruct-Turbo", "deepseek-ai/DeepSeek-V3"],
        "default_model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "format": "openai",
        "description": "Together AI。可按量付费跑开源模型",
    },
    "perplexity": {
        "name": "Perplexity",
        "base_url": "https://api.perplexity.ai",
        "models": ["sonar-pro", "sonar", "sonar-reasoning"],
        "default_model": "sonar",
        "format": "openai",
        "description": "Perplexity AI。支持联网搜索",
    },
    "cohere": {
        "name": "Cohere",
        "base_url": "https://api.cohere.ai/v1",
        "models": ["command-r-plus", "command-r", "command"],
        "default_model": "command-r",
        "format": "openai",
        "description": "Cohere。企业级 RAG 优化",
    },
    # ═══ 本地 / 自定义 ═══
    "ollama": {
        "name": "Ollama（本地运行）",
        "base_url": "http://localhost:11434/v1",
        "models": ["llama3.2", "qwen2.5", "mistral", "gemma2", "deepseek-r1"],
        "default_model": "qwen2.5",
        "format": "openai",
        "description": "完全免费、数据不出本机、无需 API Key。需先安装 Ollama",
    },
    "custom": {
        "name": "自定义（OpenAI 兼容）",
        "base_url": "",
        "models": [],
        "default_model": "",
        "format": "openai",
        "description": "填入任意兼容 OpenAI 格式的 API 地址和模型名",
    },
}

DEFAULT_PROVIDER = "deepseek"
